# Generated by Django 4.1.7 on 2023-02-22 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_app_creator_alter_appadded_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appadded",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.app"
            ),
        ),
    ]
