# Generated by Django 4.1.7 on 2023-02-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_appadded_app"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
