# Generated by Django 4.1.7 on 2023-02-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_app_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appadded",
            name="screenshot",
            field=models.ImageField(
                default="secreenshots/default.png", upload_to="screenshots"
            ),
        ),
    ]
