# Generated by Django 4.1.7 on 2023-02-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_appadded_screenshot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="app",
            name="task_completed",
        ),
        migrations.AddField(
            model_name="appadded",
            name="task_completed",
            field=models.BooleanField(default=False),
        ),
    ]
